### ISSUE TITLE
add link

### ISSUE THREAD

**Issue by fqcto** [Geekhyt/weekly#15]
name: 方圆编程
desc: 专注于前端技术的总结，努力做一名知识的传播者。
avatar: https://cdn.jsdelivr.net/gh/fqcto/images/blogs/picture/20211202152001.png
link: http://1996f.cn/

**Comment by Geekhyt** [comment]
> name: 方圆编程 desc: 专注于前端技术的总结，努力做一名知识的传播者。 avatar: https://cdn.jsdelivr.net/gh/fqcto/images/blogs/picture/20211202152001.png link: http://1996f.cn/
