### ISSUE TITLE
如果可以有rss订阅就好了 New feature proposal: rss

### ISSUE THREAD

**Issue by PinkR1ver** [Geekhyt/weekly#37]
或许可以有个rss？🧐

**Comment by tianheg** [comment]
可以用这个 https://rsshub.app/github/issue/Geekhyt/weekly

**Comment by tianheg** [comment]
项目地址 https://github.com/DIYgod/RSSHub

**Comment by Geekhyt** [comment]
> 可以用这个 https://rsshub.app/github/issue/Geekhyt/weekly
> 
> 项目地址 https://github.com/DIYgod/RSSHub

棒～
